import { z } from 'zod';
export const reflectionSchema=z.object({satisfaction:z.number().int().min(1).max(5),wentWell:z.string().max(10000).default(''),unexpected:z.string().max(10000).default(''),difficulties:z.string().max(10000).default(''),nextChange:z.string().max(10000).default(''),note:z.string().max(10000).default(''),emotions:z.array(z.string()).default([]),energy:z.number().min(1).max(5).optional()});
export const lessonSchema=z.object({title:z.string().trim().min(1,'제목을 입력해 주세요.').max(200),lessonAt:z.string(),subject:z.string().default('국어'),grade:z.string().default('2'),className:z.string().default(''),unit:z.string().default(''),objective:z.string().default(''),question:z.string().default(''),activities:z.string().default(''),difficulties:z.string().default(''),observations:z.string().default(''),tags:z.string().default(''),status:z.enum(['draft','planned','reflected']).default('draft'),change:z.string().default(''),reason:z.string().default('')});
export type Reflection=z.infer<typeof reflectionSchema>;
export type Lesson=z.infer<typeof lessonSchema>&{id:string;groupId:string;version:number;parentId?:string;reflection?:Reflection;analysis?:Analysis;editedAnalysis?:Analysis;accepted?:boolean};
export type Analysis={summary:string;strengths:{title:string;explanation:string;evidenceFields:string[]}[];improvements:{title:string;explanation:string;evidenceFields:string[]}[];nextActions:{action:string;rationale:string}[];observationQuestions:string[];safetyFlags:string[]};
export type Profile={displayName:string;schoolLevel:string;subject:string;grade:string;aiEnabled:boolean};
export function owns(owner:string,user:string){return !!user&&owner===user;}
export function nextVersion(lessons:Lesson[],groupId:string){return Math.max(0,...lessons.filter(l=>l.groupId===groupId).map(l=>l.version))+1;}
export function recommend(lessons:Lesson[],input:Partial<Lesson>){const words=(s='')=>s.toLowerCase().split(/[\s,]+/).filter(w=>w.length>1);return lessons.filter(l=>l.id!==input.id).map(l=>({l,score:(input.unit&&l.unit===input.unit?4:0)+words(input.title).filter(w=>l.title.toLowerCase().includes(w)).length+words(input.tags).filter(w=>words(l.tags).includes(w)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.l);}
